we need to define match(query,name) func
C:\SRC\GO\runescan\runes000>go test
# _/C_/SRC/GO/runescan/runes000 [_/C_/SRC/GO/runescan/runes000.test]
.\runes_test.go:48:24: undefined: match
FAIL    _/C_/SRC/GO/runescan/runes000 [build failed]