in pogram runes.go we define signature of func Parse, arg, and ret - what we want to do, and we want to get out of it:
runes.go:
func Parse(line string) string {
	return "0041"
}

runes_test.go: we import the missing type of TestParse func
import "testing" // <------
func TestParse(t *testing.T) {
	// Given
	const line= "0041;LATIN CAPITAL LETTER A;Lu;0;L;;;;;N;;;;0061;"
	// When
	got := Parse(line)
	// Then
	want := "0041"
	if want != got {
		t.Errorf("got: %v, want: %v", got, want)
	}
}

C:\SRC\GO\runescan\runes000>go test
# _/C_/SRC/GO/runescan/runes000 [_/C_/SRC/GO/runescan/runes000.test]
.\runes_test.go:9:19: undefined: testing
FAIL    _/C_/SRC/GO/runescan/runes000 [build failed]

C:\SRC\GO\runescan\runes000>go test
PASS
ok      _/C_/SRC/GO/runescan/runes000   0.466s