We want our search to be case insensitive, and order of words should not matter We add another test line to illustrate this: {"black", "BLACK CHESS KING", false},
func TestMatch(t *testing.T) {
	testCases := []struct {
		query string
		name string
		want bool
	}{		{"BLACK", "BLACK CHESS KING", true},
			{"WHITE", "BLACK CHESS KING", false},
			{"black", "BLACK CHESS KING", true},  //<------
	}

command terminal window cli  test fails, since we haven't implemented case insensitivity, and order does not matter yet:

C:\SRC\GO\runescan\runes000>go test
--- FAIL: TestMatch (0.00s)
    --- FAIL: TestMatch/black_in_BLACK_CHESS_KING (0.00s)
        runes_test.go:50: got false; want true
FAIL
exit status 1
FAIL    _/C_/SRC/GO/runescan/runes000   0.346s